### ISSUE TITLE
is there anyway to auto refresh cache after online

### ISSUE THREAD

**Issue by knight-ni** [silviu20092/azerothcore-item-upgrades#2]
the item stats changed to what it was before upgrade after character offline and online again, it seems right after refresh cache with that NPC, is there any way to finish this in player login events?

**Comment by silviu20092** [comment]
Can you provide exact steps on how to reproduce this issue? How were the item stats changed? When player logs in, item packets are sent after 3 seconds, so everything should be visually OK. Manual cache refresh using the NPC calls the exact same code as log in event, so I can't see  any differences.
