### ISSUE TITLE
Weapon DPS & damage on upgrade

### ISSUE THREAD

**Issue by dkapte** [silviu20092/azerothcore-item-upgrades#3]
Currently there is no option in the config or calculation included, to also increase the weapon min / max damage and dps, once an upgrade has been made.
This results in caster weapons being more powerful as they have flat spell power and the spellpower stat (45) can be upgraded.

If there any configuration setting that can be applied to also increase the dps / min-max dmg on the weapon upon upgrading it to a higher item level.

See example below for shadowmourne at item level 311 (dps + min/max damage remains the same as stock weapon)

![shadow](https://github.com/user-attachments/assets/af9265d1-0503-483e-92fc-24244dd8f7fa)

**Comment by silviu20092** [comment]
The entire model is designed to upgrade base stats (base item mods), and not armor, min/max damage etc. It can't be done without core modifications (from what I've seen *maybe* some more hooks are enough for this, not 100% sure though). Maybe this is something that I can work in the future, but for sure as a separate mod.

**Comment by dkapte** [comment]
Thanks for the quick response, i have implemented an alternative to this (hooked melee aura buffs based on rank purchase for melee weapons only). But again thanks for checking and looking forward to updates in the future

**Comment by silviu20092** [comment]
This was implemented in https://github.com/silviu20092/azerothcore-item-upgrades/commit/c4734b46c8c1ba87c101bd1f974c5bf12dc4adde
You will need to upgrade your AC sources to latest as a new hook was added  to make this feature possible.
